site_name: CNI Migration Tool
site_description: A tool to facilitate migration from various Kubernetes CNI solutions to Cilium
site_author: CNI Migration Tool Contributors
site_url: https://cmcconnell1.github.io/k8s-cni-migration-tool/

repo_name: cmcconnell1/k8s-cni-migration-tool
repo_url: https://github.com/cmcconnell1/k8s-cni-migration-tool
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - User Guide:
    - Assessment: user-guide/assessment.md
    - Policy Conversion: user-guide/policy-conversion.md
    - Migration Planning: user-guide/migration-planning.md
    - Validation: user-guide/validation.md
  - Migration Approaches:
    - Hybrid Approach: approaches/hybrid.md
    - Multus Approach: approaches/multus.md
    - Clean Approach: approaches/clean.md
  - Testing:
    - Minikube Testing: testing/minikube.md
    - CI/CD Pipeline: testing/ci-cd.md
  - API Reference:
    - Assessment Module: api/assessment.md
    - Policy Converter Module: api/policy-converter.md
    - Migration Planner Module: api/migration-planner.md
    - Validator Module: api/validator.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
  - git-revision-date-localized:
      type: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmcconnell1
    - icon: fontawesome/brands/slack
      link: https://kubernetes.slack.com/archives/C01TGNKF33M  # Cilium channel on K8s Slack

copyright: Copyright &copy; 2023 CNI Migration Tool Contributors
